"use client";

import { useMemo } from "react";
import { motion } from "framer-motion";
import { marked } from "marked";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { ScrollArea } from "@/components/ui/scroll-area";
import { FileText, Download, Printer } from "lucide-react";
import { Button } from "@/components/ui/button";

interface ReportViewerProps {
  content: string;
  title?: string;
  type?: "pdf" | "xray" | "medicine";
}

export function ReportViewer({
  content,
  title = "Analysis Report",
}: ReportViewerProps) {
  const htmlContent = useMemo(() => {
    if (!content) return "";
    return marked.parse(content);
  }, [content]);

  const handleDownload = () => {
    const blob = new Blob([content], { type: "text/plain" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `curasense-report-${Date.now()}.txt`;
    a.click();
    URL.revokeObjectURL(url);
  };

  const handlePrint = () => {
    const printWindow = window.open("", "_blank");
    if (printWindow) {
      printWindow.document.write(`
        <!DOCTYPE html>
        <html>
          <head>
            <title>${title} - CuraSense</title>
            <style>
              body { font-family: system-ui, sans-serif; padding: 40px; max-width: 800px; margin: 0 auto; line-height: 1.6; }
              h1, h2, h3 { color: #0f766e; }
              ul, ol { margin-left: 20px; }
              pre { background: #f1f5f9; padding: 16px; border-radius: 8px; overflow-x: auto; }
            </style>
          </head>
          <body>
            <h1>${title}</h1>
            <p style="color: #64748b;">Generated by CuraSense AI • ${new Date().toLocaleString()}</p>
            <hr style="margin: 20px 0; border: none; border-top: 1px solid #e2e8f0;" />
            ${htmlContent}
            <hr style="margin: 40px 0; border: none; border-top: 1px solid #e2e8f0;" />
            <p style="color: #94a3b8; font-size: 12px;">
              This report was generated using AI-powered analysis. Please consult with a qualified healthcare professional for medical advice.
            </p>
          </body>
        </html>
      `);
      printWindow.document.close();
      printWindow.print();
    }
  };

  return (
    <motion.div
      initial={{ opacity: 0, y: 20 }}
      animate={{ opacity: 1, y: 0 }}
      transition={{ duration: 0.5 }}
    >
      <Card className="overflow-hidden">
        <CardHeader className="border-b border-slate-200/50 bg-gradient-to-r from-teal-500/5 to-cyan-500/5 dark:border-slate-700/50">
          <div className="flex items-center justify-between">
            <div className="flex items-center gap-3">
              <div className="flex h-10 w-10 items-center justify-center rounded-xl bg-gradient-to-br from-teal-500 to-cyan-500">
                <FileText className="h-5 w-5 text-white" />
              </div>
              <div>
                <CardTitle className="text-lg">{title}</CardTitle>
                <p className="text-xs text-slate-500 dark:text-slate-400">
                  Generated {new Date().toLocaleDateString()}
                </p>
              </div>
            </div>
            <div className="flex gap-2">
              <Button variant="outline" size="sm" onClick={handleDownload}>
                <Download className="mr-2 h-4 w-4" />
                Download
              </Button>
              <Button variant="outline" size="sm" onClick={handlePrint}>
                <Printer className="mr-2 h-4 w-4" />
                Print
              </Button>
            </div>
          </div>
        </CardHeader>
        <CardContent className="p-0">
          <ScrollArea className="h-[500px]">
            <div
              className="prose prose-slate dark:prose-invert max-w-none p-6 prose-headings:text-teal-700 dark:prose-headings:text-teal-400 prose-a:text-teal-600 dark:prose-a:text-teal-400"
              dangerouslySetInnerHTML={{ __html: htmlContent }}
            />
          </ScrollArea>
        </CardContent>
      </Card>
    </motion.div>
  );
}
